// generated by github.com/moontrade/dtc-go/codegen/go at 2022-05-25 15:25:42.126453 +0800 WITA m=+0.007296918
use super::*;

pub(crate) const HISTORICAL_MARKET_DEPTH_DATA_REJECT_VLS_SIZE: usize = 20;

pub(crate) const HISTORICAL_MARKET_DEPTH_DATA_REJECT_FIXED_SIZE: usize = 108;

/// size                u16                                      = HistoricalMarketDepthDataRejectVLSSize  (20)
/// type                u16                                      = HISTORICAL_MARKET_DEPTH_DATA_REJECT  (902)
/// base_size           u16                                      = HistoricalMarketDepthDataRejectVLSSize  (20)
/// request_id          i32                                      = 0
/// reject_text         string                                   = ""
/// reject_reason_code  HistoricalPriceDataRejectReasonCodeEnum  = HPDR_UNSET  (0)
pub(crate) const HISTORICAL_MARKET_DEPTH_DATA_REJECT_VLS_DEFAULT: [u8; 20] = [
    20, 0, 134, 3, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

/// size                u16                                      = HistoricalMarketDepthDataRejectFixedSize  (108)
/// type                u16                                      = HISTORICAL_MARKET_DEPTH_DATA_REJECT  (902)
/// request_id          i32                                      = 0
/// reject_text         string96                                 = ""
/// reject_reason_code  HistoricalPriceDataRejectReasonCodeEnum  = HPDR_UNSET  (0)
pub(crate) const HISTORICAL_MARKET_DEPTH_DATA_REJECT_FIXED_DEFAULT: [u8; 108] = [
    108, 0, 134, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

pub trait HistoricalMarketDepthDataReject: Message {
    type Safe: HistoricalMarketDepthDataReject;
    type Unsafe: HistoricalMarketDepthDataReject;

    fn request_id(&self) -> i32;

    fn reject_text(&self) -> &str;

    fn reject_reason_code(&self) -> HistoricalPriceDataRejectReasonCodeEnum;

    fn set_request_id(&mut self, value: i32) -> &mut Self;

    fn set_reject_text(&mut self, value: &str) -> &mut Self;

    fn set_reject_reason_code(
        &mut self,
        value: HistoricalPriceDataRejectReasonCodeEnum,
    ) -> &mut Self;

    fn clone_safe(&self) -> Self::Safe;

    fn to_safe(self) -> Self::Safe;

    fn copy_to(&self, to: &mut impl HistoricalMarketDepthDataReject) {
        to.set_request_id(self.request_id());
        to.set_reject_text(self.reject_text());
        to.set_reject_reason_code(self.reject_reason_code());
    }
}

pub struct HistoricalMarketDepthDataRejectVLS {
    data: *const HistoricalMarketDepthDataRejectVLSData,
    capacity: usize,
}

pub struct HistoricalMarketDepthDataRejectVLSUnsafe {
    data: *const HistoricalMarketDepthDataRejectVLSData,
    capacity: usize,
}

#[repr(packed(8), C)]
pub struct HistoricalMarketDepthDataRejectVLSData {
    size: u16,
    r#type: u16,
    base_size: u16,
    request_id: i32,
    reject_text: VLS,
    reject_reason_code: HistoricalPriceDataRejectReasonCodeEnum,
}

pub struct HistoricalMarketDepthDataRejectFixed {
    data: *const HistoricalMarketDepthDataRejectFixedData,
}

pub struct HistoricalMarketDepthDataRejectFixedUnsafe {
    data: *const HistoricalMarketDepthDataRejectFixedData,
}

#[repr(packed(8), C)]
pub struct HistoricalMarketDepthDataRejectFixedData {
    size: u16,
    r#type: u16,
    request_id: i32,
    reject_text: [u8; 96],
    reject_reason_code: HistoricalPriceDataRejectReasonCodeEnum,
}

impl HistoricalMarketDepthDataRejectVLSData {
    pub fn new() -> Self {
        Self {
            size: 20u16.to_le(),
            r#type: HISTORICAL_MARKET_DEPTH_DATA_REJECT.to_le(),
            base_size: 20u16.to_le(),
            request_id: 0i32,
            reject_text: crate::message::VLS::new(),
            reject_reason_code: HistoricalPriceDataRejectReasonCodeEnum::HpdrUnset.to_le(),
        }
    }
}

impl HistoricalMarketDepthDataRejectFixedData {
    pub fn new() -> Self {
        Self {
            size: 108u16.to_le(),
            r#type: HISTORICAL_MARKET_DEPTH_DATA_REJECT.to_le(),
            request_id: 0i32,
            reject_text: [0; 96],
            reject_reason_code: HistoricalPriceDataRejectReasonCodeEnum::HpdrUnset.to_le(),
        }
    }
}

unsafe impl Send for HistoricalMarketDepthDataRejectFixed {}
unsafe impl Send for HistoricalMarketDepthDataRejectFixedUnsafe {}
unsafe impl Send for HistoricalMarketDepthDataRejectFixedData {}
unsafe impl Send for HistoricalMarketDepthDataRejectVLS {}
unsafe impl Send for HistoricalMarketDepthDataRejectVLSUnsafe {}
unsafe impl Send for HistoricalMarketDepthDataRejectVLSData {}

impl Drop for HistoricalMarketDepthDataRejectFixed {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Drop for HistoricalMarketDepthDataRejectFixedUnsafe {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Drop for HistoricalMarketDepthDataRejectVLS {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Drop for HistoricalMarketDepthDataRejectVLSUnsafe {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Clone for HistoricalMarketDepthDataRejectFixed {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Clone for HistoricalMarketDepthDataRejectFixedUnsafe {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Clone for HistoricalMarketDepthDataRejectVLS {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Clone for HistoricalMarketDepthDataRejectVLSUnsafe {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Into<Vec<u8>> for HistoricalMarketDepthDataRejectFixed {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl Into<Vec<u8>> for HistoricalMarketDepthDataRejectFixedUnsafe {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl Into<Vec<u8>> for HistoricalMarketDepthDataRejectVLS {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl Into<Vec<u8>> for HistoricalMarketDepthDataRejectVLSUnsafe {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl core::ops::Deref for HistoricalMarketDepthDataRejectFixed {
    type Target = HistoricalMarketDepthDataRejectFixedData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for HistoricalMarketDepthDataRejectFixed {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl core::ops::Deref for HistoricalMarketDepthDataRejectFixedUnsafe {
    type Target = HistoricalMarketDepthDataRejectFixedData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for HistoricalMarketDepthDataRejectFixedUnsafe {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl core::ops::Deref for HistoricalMarketDepthDataRejectVLS {
    type Target = HistoricalMarketDepthDataRejectVLSData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for HistoricalMarketDepthDataRejectVLS {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl core::ops::Deref for HistoricalMarketDepthDataRejectVLSUnsafe {
    type Target = HistoricalMarketDepthDataRejectVLSData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for HistoricalMarketDepthDataRejectVLSUnsafe {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl crate::Message for HistoricalMarketDepthDataRejectFixed {
    type Data = HistoricalMarketDepthDataRejectFixedData;

    const BASE_SIZE: usize = 108;
    const BASE_SIZE_OFFSET: isize = 0;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(
                Self::BASE_SIZE,
                HistoricalMarketDepthDataRejectFixedData::new(),
            ),
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, _: usize) -> Self {
        Self {
            data: data as *const HistoricalMarketDepthDataRejectFixedData,
        }
    }
}
impl crate::Message for HistoricalMarketDepthDataRejectFixedUnsafe {
    type Data = HistoricalMarketDepthDataRejectFixedData;

    const BASE_SIZE: usize = 108;
    const BASE_SIZE_OFFSET: isize = 0;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(
                Self::BASE_SIZE,
                HistoricalMarketDepthDataRejectFixedData::new(),
            ),
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, _: usize) -> Self {
        Self {
            data: data as *const HistoricalMarketDepthDataRejectFixedData,
        }
    }
}
impl crate::Message for HistoricalMarketDepthDataRejectVLS {
    type Data = HistoricalMarketDepthDataRejectVLSData;

    const BASE_SIZE: usize = 20;
    const BASE_SIZE_OFFSET: isize = 4;
    const DEFAULT_CAPACITY: usize = Self::BASE_SIZE * 2;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(
                Self::BASE_SIZE,
                HistoricalMarketDepthDataRejectVLSData::new(),
            ),
            capacity: Self::DEFAULT_CAPACITY,
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.base_size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        self.capacity as u16
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, capacity: usize) -> Self {
        Self {
            data: data as *const HistoricalMarketDepthDataRejectVLSData,
            capacity,
        }
    }
}

impl crate::VLSMessage for HistoricalMarketDepthDataRejectVLS {
    #[inline]
    unsafe fn set_ptr(&mut self, value: *const u8) {
        self.data = value as *const HistoricalMarketDepthDataRejectVLSData;
    }

    #[inline]
    fn set_capacity(&mut self, capacity: u16) {
        self.capacity = capacity as usize;
    }

    #[inline]
    fn set_size(&mut self, size: u16) {
        self.size = size.to_le();
    }
}
impl crate::Message for HistoricalMarketDepthDataRejectVLSUnsafe {
    type Data = HistoricalMarketDepthDataRejectVLSData;

    const BASE_SIZE: usize = 20;
    const BASE_SIZE_OFFSET: isize = 4;
    const DEFAULT_CAPACITY: usize = Self::BASE_SIZE * 2;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(
                Self::BASE_SIZE,
                HistoricalMarketDepthDataRejectVLSData::new(),
            ),
            capacity: Self::DEFAULT_CAPACITY,
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.base_size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        self.capacity as u16
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, capacity: usize) -> Self {
        Self {
            data: data as *const HistoricalMarketDepthDataRejectVLSData,
            capacity,
        }
    }
}

impl crate::VLSMessage for HistoricalMarketDepthDataRejectVLSUnsafe {
    #[inline]
    unsafe fn set_ptr(&mut self, value: *const u8) {
        self.data = value as *const HistoricalMarketDepthDataRejectVLSData;
    }

    #[inline]
    fn set_capacity(&mut self, capacity: u16) {
        self.capacity = capacity as usize;
    }

    #[inline]
    fn set_size(&mut self, size: u16) {
        self.size = size.to_le();
    }
}
impl HistoricalMarketDepthDataReject for HistoricalMarketDepthDataRejectVLS {
    type Safe = HistoricalMarketDepthDataRejectVLS;
    type Unsafe = HistoricalMarketDepthDataRejectVLSUnsafe;

    fn request_id(&self) -> i32 {
        i32::from_le(self.request_id)
    }

    fn reject_text(&self) -> &str {
        get_vls(self, self.reject_text)
    }

    fn reject_reason_code(&self) -> HistoricalPriceDataRejectReasonCodeEnum {
        HistoricalPriceDataRejectReasonCodeEnum::from_le(self.reject_reason_code)
    }

    fn set_request_id(&mut self, value: i32) -> &mut Self {
        self.request_id = value.to_le();
        self
    }

    fn set_reject_text(&mut self, value: &str) -> &mut Self {
        self.reject_text = set_vls(self, self.reject_text, value);
        self
    }

    fn set_reject_reason_code(
        &mut self,
        value: HistoricalPriceDataRejectReasonCodeEnum,
    ) -> &mut Self {
        self.reject_reason_code = unsafe { core::mem::transmute((value as i16).to_le()) };
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        self
    }
}

impl HistoricalMarketDepthDataReject for HistoricalMarketDepthDataRejectVLSUnsafe {
    type Safe = HistoricalMarketDepthDataRejectVLS;
    type Unsafe = HistoricalMarketDepthDataRejectVLSUnsafe;

    fn request_id(&self) -> i32 {
        if self.is_out_of_bounds(12) {
            0i32
        } else {
            i32::from_le(self.request_id)
        }
    }

    fn reject_text(&self) -> &str {
        if self.is_out_of_bounds(16) {
            ""
        } else {
            get_vls(self, self.reject_text)
        }
    }

    fn reject_reason_code(&self) -> HistoricalPriceDataRejectReasonCodeEnum {
        if self.is_out_of_bounds(18) {
            HistoricalPriceDataRejectReasonCodeEnum::HpdrUnset.to_le()
        } else {
            HistoricalPriceDataRejectReasonCodeEnum::from_le(self.reject_reason_code)
        }
    }

    fn set_request_id(&mut self, value: i32) -> &mut Self {
        if !self.is_out_of_bounds(12) {
            self.request_id = value.to_le();
        }
        self
    }

    fn set_reject_text(&mut self, value: &str) -> &mut Self {
        if !self.is_out_of_bounds(16) {
            self.reject_text = set_vls(self, self.reject_text, value);
        }
        self
    }

    fn set_reject_reason_code(
        &mut self,
        value: HistoricalPriceDataRejectReasonCodeEnum,
    ) -> &mut Self {
        if !self.is_out_of_bounds(18) {
            self.reject_reason_code = unsafe { core::mem::transmute((value as i16).to_le()) };
        }
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }
}

impl HistoricalMarketDepthDataReject for HistoricalMarketDepthDataRejectFixed {
    type Safe = HistoricalMarketDepthDataRejectFixed;
    type Unsafe = HistoricalMarketDepthDataRejectFixedUnsafe;

    fn request_id(&self) -> i32 {
        i32::from_le(self.request_id)
    }

    fn reject_text(&self) -> &str {
        get_fixed(&self.reject_text[..])
    }

    fn reject_reason_code(&self) -> HistoricalPriceDataRejectReasonCodeEnum {
        HistoricalPriceDataRejectReasonCodeEnum::from_le(self.reject_reason_code)
    }

    fn set_request_id(&mut self, value: i32) -> &mut Self {
        self.request_id = value.to_le();
        self
    }

    fn set_reject_text(&mut self, value: &str) -> &mut Self {
        set_fixed(&mut self.reject_text[..], value);
        self
    }

    fn set_reject_reason_code(
        &mut self,
        value: HistoricalPriceDataRejectReasonCodeEnum,
    ) -> &mut Self {
        self.reject_reason_code = unsafe { core::mem::transmute((value as i16).to_le()) };
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        self
    }
}

impl HistoricalMarketDepthDataReject for HistoricalMarketDepthDataRejectFixedUnsafe {
    type Safe = HistoricalMarketDepthDataRejectFixed;
    type Unsafe = HistoricalMarketDepthDataRejectFixedUnsafe;

    fn request_id(&self) -> i32 {
        if self.is_out_of_bounds(8) {
            0i32
        } else {
            i32::from_le(self.request_id)
        }
    }

    fn reject_text(&self) -> &str {
        if self.is_out_of_bounds(104) {
            ""
        } else {
            get_fixed(&self.reject_text[..])
        }
    }

    fn reject_reason_code(&self) -> HistoricalPriceDataRejectReasonCodeEnum {
        if self.is_out_of_bounds(106) {
            HistoricalPriceDataRejectReasonCodeEnum::HpdrUnset.to_le()
        } else {
            HistoricalPriceDataRejectReasonCodeEnum::from_le(self.reject_reason_code)
        }
    }

    fn set_request_id(&mut self, value: i32) -> &mut Self {
        if !self.is_out_of_bounds(8) {
            self.request_id = value.to_le();
        }
        self
    }

    fn set_reject_text(&mut self, value: &str) -> &mut Self {
        if !self.is_out_of_bounds(104) {
            set_fixed(&mut self.reject_text[..], value);
        }
        self
    }

    fn set_reject_reason_code(
        &mut self,
        value: HistoricalPriceDataRejectReasonCodeEnum,
    ) -> &mut Self {
        if !self.is_out_of_bounds(106) {
            self.reject_reason_code = unsafe { core::mem::transmute((value as i16).to_le()) };
        }
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    #[test]
    pub(crate) fn layout() {
        unsafe {
            assert_eq!(
                108usize,
                core::mem::size_of::<HistoricalMarketDepthDataRejectFixedData>(),
                "HistoricalMarketDepthDataRejectFixedData sizeof expected {:} but was {:}",
                108usize,
                core::mem::size_of::<HistoricalMarketDepthDataRejectFixedData>()
            );
            assert_eq!(
                108u16,
                HistoricalMarketDepthDataRejectFixed::new().size(),
                "HistoricalMarketDepthDataRejectFixed sizeof expected {:} but was {:}",
                108u16,
                HistoricalMarketDepthDataRejectFixed::new().size(),
            );
            assert_eq!(
                HISTORICAL_MARKET_DEPTH_DATA_REJECT,
                HistoricalMarketDepthDataRejectFixed::new().r#type(),
                "HistoricalMarketDepthDataRejectFixed type expected {:} but was {:}",
                HISTORICAL_MARKET_DEPTH_DATA_REJECT,
                HistoricalMarketDepthDataRejectFixed::new().r#type(),
            );
            assert_eq!(
                902u16,
                HistoricalMarketDepthDataRejectFixed::new().r#type(),
                "HistoricalMarketDepthDataRejectFixed type expected {:} but was {:}",
                902u16,
                HistoricalMarketDepthDataRejectFixed::new().r#type(),
            );
            let d = HistoricalMarketDepthDataRejectFixedData::new();
            let p = (&d as *const _ as *const u8).offset(0) as usize;
            assert_eq!(
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
                "size offset expected {:} but was {:}",
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
            );
            assert_eq!(
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
                "type offset expected {:} but was {:}",
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
            );
            assert_eq!(
                4usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
                "request_id offset expected {:} but was {:}",
                4usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
            );
            assert_eq!(
                8usize,
                (core::ptr::addr_of!(d.reject_text) as usize) - p,
                "reject_text offset expected {:} but was {:}",
                8usize,
                (core::ptr::addr_of!(d.reject_text) as usize) - p,
            );
            assert_eq!(
                104usize,
                (core::ptr::addr_of!(d.reject_reason_code) as usize) - p,
                "reject_reason_code offset expected {:} but was {:}",
                104usize,
                (core::ptr::addr_of!(d.reject_reason_code) as usize) - p,
            );
        }
        unsafe {
            assert_eq!(
                20usize,
                core::mem::size_of::<HistoricalMarketDepthDataRejectVLSData>(),
                "HistoricalMarketDepthDataRejectVLSData sizeof expected {:} but was {:}",
                20usize,
                core::mem::size_of::<HistoricalMarketDepthDataRejectVLSData>()
            );
            assert_eq!(
                20u16,
                HistoricalMarketDepthDataRejectVLS::new().size(),
                "HistoricalMarketDepthDataRejectVLS sizeof expected {:} but was {:}",
                20u16,
                HistoricalMarketDepthDataRejectVLS::new().size(),
            );
            assert_eq!(
                HISTORICAL_MARKET_DEPTH_DATA_REJECT,
                HistoricalMarketDepthDataRejectVLS::new().r#type(),
                "HistoricalMarketDepthDataRejectVLS type expected {:} but was {:}",
                HISTORICAL_MARKET_DEPTH_DATA_REJECT,
                HistoricalMarketDepthDataRejectVLS::new().r#type(),
            );
            assert_eq!(
                902u16,
                HistoricalMarketDepthDataRejectVLS::new().r#type(),
                "HistoricalMarketDepthDataRejectVLS type expected {:} but was {:}",
                902u16,
                HistoricalMarketDepthDataRejectVLS::new().r#type(),
            );
            let d = HistoricalMarketDepthDataRejectVLSData::new();
            let p = (&d as *const _ as *const u8).offset(0) as usize;
            assert_eq!(
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
                "size offset expected {:} but was {:}",
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
            );
            assert_eq!(
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
                "type offset expected {:} but was {:}",
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
            );
            assert_eq!(
                4usize,
                (core::ptr::addr_of!(d.base_size) as usize) - p,
                "base_size offset expected {:} but was {:}",
                4usize,
                (core::ptr::addr_of!(d.base_size) as usize) - p,
            );
            assert_eq!(
                8usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
                "request_id offset expected {:} but was {:}",
                8usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
            );
            assert_eq!(
                12usize,
                (core::ptr::addr_of!(d.reject_text) as usize) - p,
                "reject_text offset expected {:} but was {:}",
                12usize,
                (core::ptr::addr_of!(d.reject_text) as usize) - p,
            );
            assert_eq!(
                16usize,
                (core::ptr::addr_of!(d.reject_reason_code) as usize) - p,
                "reject_reason_code offset expected {:} but was {:}",
                16usize,
                (core::ptr::addr_of!(d.reject_reason_code) as usize) - p,
            );
        }
    }
}
