// generated by github.com/moontrade/dtc-go/codegen/go at 2022-05-25 15:25:42.126453 +0800 WITA m=+0.007296918
use super::*;

pub(crate) const MARGIN_DATA_REQUEST_VLS_SIZE: usize = 18;

/// size           u16     = MarginDataRequestVLSSize  (18)
/// type           u16     = MARGIN_DATA_REQUEST  (10141)
/// base_size      u16     = MarginDataRequestVLSSize  (18)
/// request_id     i32     = 0
/// trade_account  string  = ""
/// symbol         string  = ""
pub(crate) const MARGIN_DATA_REQUEST_VLS_DEFAULT: [u8; 18] =
    [18, 0, 157, 39, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

pub trait MarginDataRequest: Message {
    type Safe: MarginDataRequest;
    type Unsafe: MarginDataRequest;

    fn request_id(&self) -> i32;

    fn trade_account(&self) -> &str;

    fn symbol(&self) -> &str;

    fn set_request_id(&mut self, value: i32) -> &mut Self;

    fn set_trade_account(&mut self, value: &str) -> &mut Self;

    fn set_symbol(&mut self, value: &str) -> &mut Self;

    fn clone_safe(&self) -> Self::Safe;

    fn to_safe(self) -> Self::Safe;

    fn copy_to(&self, to: &mut impl MarginDataRequest) {
        to.set_request_id(self.request_id());
        to.set_trade_account(self.trade_account());
        to.set_symbol(self.symbol());
    }
}

pub struct MarginDataRequestVLS {
    data: *const MarginDataRequestVLSData,
    capacity: usize,
}

pub struct MarginDataRequestVLSUnsafe {
    data: *const MarginDataRequestVLSData,
    capacity: usize,
}

#[repr(packed(1), C)]
pub struct MarginDataRequestVLSData {
    size: u16,
    r#type: u16,
    base_size: u16,
    request_id: i32,
    trade_account: VLS,
    symbol: VLS,
}

impl MarginDataRequestVLSData {
    pub fn new() -> Self {
        Self {
            size: 18u16.to_le(),
            r#type: MARGIN_DATA_REQUEST.to_le(),
            base_size: 18u16.to_le(),
            request_id: 0i32.to_le(),
            trade_account: crate::message::VLS::new(),
            symbol: crate::message::VLS::new(),
        }
    }
}

unsafe impl Send for MarginDataRequestVLS {}
unsafe impl Send for MarginDataRequestVLSUnsafe {}
unsafe impl Send for MarginDataRequestVLSData {}

impl Drop for MarginDataRequestVLS {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Drop for MarginDataRequestVLSUnsafe {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Clone for MarginDataRequestVLS {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Clone for MarginDataRequestVLSUnsafe {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Into<Vec<u8>> for MarginDataRequestVLS {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl Into<Vec<u8>> for MarginDataRequestVLSUnsafe {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl core::ops::Deref for MarginDataRequestVLS {
    type Target = MarginDataRequestVLSData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for MarginDataRequestVLS {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl core::ops::Deref for MarginDataRequestVLSUnsafe {
    type Target = MarginDataRequestVLSData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for MarginDataRequestVLSUnsafe {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl crate::Message for MarginDataRequestVLS {
    type Data = MarginDataRequestVLSData;

    const BASE_SIZE: usize = 18;
    const BASE_SIZE_OFFSET: isize = 4;
    const DEFAULT_CAPACITY: usize = Self::BASE_SIZE * 2;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(Self::BASE_SIZE, MarginDataRequestVLSData::new()),
            capacity: Self::DEFAULT_CAPACITY,
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.base_size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        self.capacity as u16
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, capacity: usize) -> Self {
        Self {
            data: data as *const MarginDataRequestVLSData,
            capacity,
        }
    }
}

impl crate::VLSMessage for MarginDataRequestVLS {
    #[inline]
    unsafe fn set_ptr(&mut self, value: *const u8) {
        self.data = value as *const MarginDataRequestVLSData;
    }

    #[inline]
    fn set_capacity(&mut self, capacity: u16) {
        self.capacity = capacity as usize;
    }

    #[inline]
    fn set_size(&mut self, size: u16) {
        self.size = size.to_le();
    }
}
impl crate::Message for MarginDataRequestVLSUnsafe {
    type Data = MarginDataRequestVLSData;

    const BASE_SIZE: usize = 18;
    const BASE_SIZE_OFFSET: isize = 4;
    const DEFAULT_CAPACITY: usize = Self::BASE_SIZE * 2;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(Self::BASE_SIZE, MarginDataRequestVLSData::new()),
            capacity: Self::DEFAULT_CAPACITY,
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.base_size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        self.capacity as u16
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, capacity: usize) -> Self {
        Self {
            data: data as *const MarginDataRequestVLSData,
            capacity,
        }
    }
}

impl crate::VLSMessage for MarginDataRequestVLSUnsafe {
    #[inline]
    unsafe fn set_ptr(&mut self, value: *const u8) {
        self.data = value as *const MarginDataRequestVLSData;
    }

    #[inline]
    fn set_capacity(&mut self, capacity: u16) {
        self.capacity = capacity as usize;
    }

    #[inline]
    fn set_size(&mut self, size: u16) {
        self.size = size.to_le();
    }
}
impl MarginDataRequest for MarginDataRequestVLS {
    type Safe = MarginDataRequestVLS;
    type Unsafe = MarginDataRequestVLSUnsafe;

    fn request_id(&self) -> i32 {
        i32::from_le(self.request_id)
    }

    fn trade_account(&self) -> &str {
        get_vls(self, self.trade_account)
    }

    fn symbol(&self) -> &str {
        get_vls(self, self.symbol)
    }

    fn set_request_id(&mut self, value: i32) -> &mut Self {
        self.request_id = value.to_le();
        self
    }

    fn set_trade_account(&mut self, value: &str) -> &mut Self {
        self.trade_account = set_vls(self, self.trade_account, value);
        self
    }

    fn set_symbol(&mut self, value: &str) -> &mut Self {
        self.symbol = set_vls(self, self.symbol, value);
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        self
    }
}

impl MarginDataRequest for MarginDataRequestVLSUnsafe {
    type Safe = MarginDataRequestVLS;
    type Unsafe = MarginDataRequestVLSUnsafe;

    fn request_id(&self) -> i32 {
        if self.is_out_of_bounds(10) {
            0i32.to_le()
        } else {
            i32::from_le(self.request_id)
        }
    }

    fn trade_account(&self) -> &str {
        if self.is_out_of_bounds(14) {
            ""
        } else {
            get_vls(self, self.trade_account)
        }
    }

    fn symbol(&self) -> &str {
        if self.is_out_of_bounds(18) {
            ""
        } else {
            get_vls(self, self.symbol)
        }
    }

    fn set_request_id(&mut self, value: i32) -> &mut Self {
        if !self.is_out_of_bounds(10) {
            self.request_id = value.to_le();
        }
        self
    }

    fn set_trade_account(&mut self, value: &str) -> &mut Self {
        if !self.is_out_of_bounds(14) {
            self.trade_account = set_vls(self, self.trade_account, value);
        }
        self
    }

    fn set_symbol(&mut self, value: &str) -> &mut Self {
        if !self.is_out_of_bounds(18) {
            self.symbol = set_vls(self, self.symbol, value);
        }
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    #[test]
    pub(crate) fn layout() {
        unsafe {
            assert_eq!(
                18usize,
                core::mem::size_of::<MarginDataRequestVLSData>(),
                "MarginDataRequestVLSData sizeof expected {:} but was {:}",
                18usize,
                core::mem::size_of::<MarginDataRequestVLSData>()
            );
            assert_eq!(
                18u16,
                MarginDataRequestVLS::new().size(),
                "MarginDataRequestVLS sizeof expected {:} but was {:}",
                18u16,
                MarginDataRequestVLS::new().size(),
            );
            assert_eq!(
                MARGIN_DATA_REQUEST,
                MarginDataRequestVLS::new().r#type(),
                "MarginDataRequestVLS type expected {:} but was {:}",
                MARGIN_DATA_REQUEST,
                MarginDataRequestVLS::new().r#type(),
            );
            assert_eq!(
                10141u16,
                MarginDataRequestVLS::new().r#type(),
                "MarginDataRequestVLS type expected {:} but was {:}",
                10141u16,
                MarginDataRequestVLS::new().r#type(),
            );
            let d = MarginDataRequestVLSData::new();
            let p = (&d as *const _ as *const u8).offset(0) as usize;
            assert_eq!(
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
                "size offset expected {:} but was {:}",
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
            );
            assert_eq!(
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
                "type offset expected {:} but was {:}",
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
            );
            assert_eq!(
                4usize,
                (core::ptr::addr_of!(d.base_size) as usize) - p,
                "base_size offset expected {:} but was {:}",
                4usize,
                (core::ptr::addr_of!(d.base_size) as usize) - p,
            );
            assert_eq!(
                6usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
                "request_id offset expected {:} but was {:}",
                6usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
            );
            assert_eq!(
                10usize,
                (core::ptr::addr_of!(d.trade_account) as usize) - p,
                "trade_account offset expected {:} but was {:}",
                10usize,
                (core::ptr::addr_of!(d.trade_account) as usize) - p,
            );
            assert_eq!(
                14usize,
                (core::ptr::addr_of!(d.symbol) as usize) - p,
                "symbol offset expected {:} but was {:}",
                14usize,
                (core::ptr::addr_of!(d.symbol) as usize) - p,
            );
        }
    }
}
