// generated by github.com/moontrade/dtc-go/codegen/go at 2022-05-25 15:25:42.126453 +0800 WITA m=+0.007296918
use super::*;

pub(crate) const SECURITY_DEFINITION_REJECT_VLS_SIZE: usize = 16;

pub(crate) const SECURITY_DEFINITION_REJECT_FIXED_SIZE: usize = 104;

/// size         u16     = SecurityDefinitionRejectVLSSize  (16)
/// type         u16     = SECURITY_DEFINITION_REJECT  (509)
/// base_size    u16     = SecurityDefinitionRejectVLSSize  (16)
/// request_id   i32     = 0
/// reject_text  string  = ""
pub(crate) const SECURITY_DEFINITION_REJECT_VLS_DEFAULT: [u8; 16] =
    [16, 0, 253, 1, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

/// size         u16       = SecurityDefinitionRejectFixedSize  (104)
/// type         u16       = SECURITY_DEFINITION_REJECT  (509)
/// request_id   i32       = 0
/// reject_text  string96  = ""
pub(crate) const SECURITY_DEFINITION_REJECT_FIXED_DEFAULT: [u8; 104] = [
    104, 0, 253, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

/// This is a message from the Server to the Client indicating the Server
/// is rejecting one of the following messages: SymbolsForExchangeRequestVLS,
/// UnderlyingSymbolsForExchangeRequestVLS, SymbolsForUnderlyingRequestVLS,
/// SecurityDefinitionForSymbolRequestVLS, SymbolSearchRequestVLS.
///
/// If there are no symbols to send in response to one of these messages above,
/// then the Server should not send a SecurityDefinitionRejectVLS message
/// and instead send a SecurityDefinitionResponseVLS with only the RequestID
/// and IsFinalMessage fields set. This will be a clear indication to the
/// Client that the request returned no Symbols.
pub trait SecurityDefinitionReject: Message {
    type Safe: SecurityDefinitionReject;
    type Unsafe: SecurityDefinitionReject;

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn request_id(&self) -> i32;

    /// Text reason for rejection.
    fn reject_text(&self) -> &str;

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn set_request_id(&mut self, value: i32) -> &mut Self;

    /// Text reason for rejection.
    fn set_reject_text(&mut self, value: &str) -> &mut Self;

    fn clone_safe(&self) -> Self::Safe;

    fn to_safe(self) -> Self::Safe;

    fn copy_to(&self, to: &mut impl SecurityDefinitionReject) {
        to.set_request_id(self.request_id());
        to.set_reject_text(self.reject_text());
    }
}

/// This is a message from the Server to the Client indicating the Server
/// is rejecting one of the following messages: SymbolsForExchangeRequestVLS,
/// UnderlyingSymbolsForExchangeRequestVLS, SymbolsForUnderlyingRequestVLS,
/// SecurityDefinitionForSymbolRequestVLS, SymbolSearchRequestVLS.
///
/// If there are no symbols to send in response to one of these messages above,
/// then the Server should not send a SecurityDefinitionRejectVLS message
/// and instead send a SecurityDefinitionResponseVLS with only the RequestID
/// and IsFinalMessage fields set. This will be a clear indication to the
/// Client that the request returned no Symbols.
pub struct SecurityDefinitionRejectVLS {
    data: *const SecurityDefinitionRejectVLSData,
    capacity: usize,
}

pub struct SecurityDefinitionRejectVLSUnsafe {
    data: *const SecurityDefinitionRejectVLSData,
    capacity: usize,
}

#[repr(packed(8), C)]
pub struct SecurityDefinitionRejectVLSData {
    size: u16,
    r#type: u16,
    base_size: u16,
    request_id: i32,
    reject_text: VLS,
}

/// This is a message from the Server to the Client indicating the Server
/// is rejecting one of the following messages: SymbolsForExchangeRequestVLS,
/// UnderlyingSymbolsForExchangeRequestVLS, SymbolsForUnderlyingRequestVLS,
/// SecurityDefinitionForSymbolRequestVLS, SymbolSearchRequestVLS.
///
/// If there are no symbols to send in response to one of these messages above,
/// then the Server should not send a SecurityDefinitionRejectVLS message
/// and instead send a SecurityDefinitionResponseVLS with only the RequestID
/// and IsFinalMessage fields set. This will be a clear indication to the
/// Client that the request returned no Symbols.
pub struct SecurityDefinitionRejectFixed {
    data: *const SecurityDefinitionRejectFixedData,
}

pub struct SecurityDefinitionRejectFixedUnsafe {
    data: *const SecurityDefinitionRejectFixedData,
}

#[repr(packed(8), C)]
pub struct SecurityDefinitionRejectFixedData {
    size: u16,
    r#type: u16,
    request_id: i32,
    reject_text: [u8; 96],
}

impl SecurityDefinitionRejectVLSData {
    pub fn new() -> Self {
        Self {
            size: 16u16.to_le(),
            r#type: SECURITY_DEFINITION_REJECT.to_le(),
            base_size: 16u16.to_le(),
            request_id: 0i32,
            reject_text: crate::message::VLS::new(),
        }
    }
}

impl SecurityDefinitionRejectFixedData {
    pub fn new() -> Self {
        Self {
            size: 104u16.to_le(),
            r#type: SECURITY_DEFINITION_REJECT.to_le(),
            request_id: 0i32,
            reject_text: [0; 96],
        }
    }
}

unsafe impl Send for SecurityDefinitionRejectFixed {}
unsafe impl Send for SecurityDefinitionRejectFixedUnsafe {}
unsafe impl Send for SecurityDefinitionRejectFixedData {}
unsafe impl Send for SecurityDefinitionRejectVLS {}
unsafe impl Send for SecurityDefinitionRejectVLSUnsafe {}
unsafe impl Send for SecurityDefinitionRejectVLSData {}

impl Drop for SecurityDefinitionRejectFixed {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Drop for SecurityDefinitionRejectFixedUnsafe {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Drop for SecurityDefinitionRejectVLS {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Drop for SecurityDefinitionRejectVLSUnsafe {
    #[inline]
    fn drop(&mut self) {
        crate::deallocate(self.data as *mut u8, self.capacity() as usize);
    }
}

impl Clone for SecurityDefinitionRejectFixed {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Clone for SecurityDefinitionRejectFixedUnsafe {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Clone for SecurityDefinitionRejectVLS {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Clone for SecurityDefinitionRejectVLSUnsafe {
    #[inline]
    fn clone(&self) -> Self {
        let mut c = Self::new();
        self.copy_to(&mut c);
        c
    }
}

impl Into<Vec<u8>> for SecurityDefinitionRejectFixed {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl Into<Vec<u8>> for SecurityDefinitionRejectFixedUnsafe {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl Into<Vec<u8>> for SecurityDefinitionRejectVLS {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl Into<Vec<u8>> for SecurityDefinitionRejectVLSUnsafe {
    #[inline]
    fn into(self) -> Vec<u8> {
        self.into_vec()
    }
}

impl core::ops::Deref for SecurityDefinitionRejectFixed {
    type Target = SecurityDefinitionRejectFixedData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for SecurityDefinitionRejectFixed {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl core::ops::Deref for SecurityDefinitionRejectFixedUnsafe {
    type Target = SecurityDefinitionRejectFixedData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for SecurityDefinitionRejectFixedUnsafe {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl core::ops::Deref for SecurityDefinitionRejectVLS {
    type Target = SecurityDefinitionRejectVLSData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for SecurityDefinitionRejectVLS {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl core::ops::Deref for SecurityDefinitionRejectVLSUnsafe {
    type Target = SecurityDefinitionRejectVLSData;

    #[inline]
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.data }
    }
}

impl core::ops::DerefMut for SecurityDefinitionRejectVLSUnsafe {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *(self.data as *mut Self::Target) }
    }
}

impl crate::Message for SecurityDefinitionRejectFixed {
    type Data = SecurityDefinitionRejectFixedData;

    const BASE_SIZE: usize = 104;
    const BASE_SIZE_OFFSET: isize = 0;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(Self::BASE_SIZE, SecurityDefinitionRejectFixedData::new()),
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, _: usize) -> Self {
        Self {
            data: data as *const SecurityDefinitionRejectFixedData,
        }
    }
}
impl crate::Message for SecurityDefinitionRejectFixedUnsafe {
    type Data = SecurityDefinitionRejectFixedData;

    const BASE_SIZE: usize = 104;
    const BASE_SIZE_OFFSET: isize = 0;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(Self::BASE_SIZE, SecurityDefinitionRejectFixedData::new()),
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, _: usize) -> Self {
        Self {
            data: data as *const SecurityDefinitionRejectFixedData,
        }
    }
}
impl crate::Message for SecurityDefinitionRejectVLS {
    type Data = SecurityDefinitionRejectVLSData;

    const BASE_SIZE: usize = 16;
    const BASE_SIZE_OFFSET: isize = 4;
    const DEFAULT_CAPACITY: usize = Self::BASE_SIZE * 2;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(Self::BASE_SIZE, SecurityDefinitionRejectVLSData::new()),
            capacity: Self::DEFAULT_CAPACITY,
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.base_size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        self.capacity as u16
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, capacity: usize) -> Self {
        Self {
            data: data as *const SecurityDefinitionRejectVLSData,
            capacity,
        }
    }
}

impl crate::VLSMessage for SecurityDefinitionRejectVLS {
    #[inline]
    unsafe fn set_ptr(&mut self, value: *const u8) {
        self.data = value as *const SecurityDefinitionRejectVLSData;
    }

    #[inline]
    fn set_capacity(&mut self, capacity: u16) {
        self.capacity = capacity as usize;
    }

    #[inline]
    fn set_size(&mut self, size: u16) {
        self.size = size.to_le();
    }
}
impl crate::Message for SecurityDefinitionRejectVLSUnsafe {
    type Data = SecurityDefinitionRejectVLSData;

    const BASE_SIZE: usize = 16;
    const BASE_SIZE_OFFSET: isize = 4;
    const DEFAULT_CAPACITY: usize = Self::BASE_SIZE * 2;

    #[inline]
    fn new() -> Self {
        Self {
            data: crate::allocate(Self::BASE_SIZE, SecurityDefinitionRejectVLSData::new()),
            capacity: Self::DEFAULT_CAPACITY,
        }
    }

    #[inline]
    fn size(&self) -> u16 {
        u16::from_le(self.size)
    }

    #[inline]
    fn r#type(&self) -> u16 {
        u16::from_le(self.r#type)
    }

    #[inline]
    fn base_size(&self) -> u16 {
        u16::from_le(self.base_size)
    }

    #[inline]
    fn capacity(&self) -> u16 {
        self.capacity as u16
    }

    #[inline]
    unsafe fn as_ptr(&self) -> *const Self::Data {
        self.data
    }

    #[inline]
    unsafe fn from_raw_parts(data: *const u8, capacity: usize) -> Self {
        Self {
            data: data as *const SecurityDefinitionRejectVLSData,
            capacity,
        }
    }
}

impl crate::VLSMessage for SecurityDefinitionRejectVLSUnsafe {
    #[inline]
    unsafe fn set_ptr(&mut self, value: *const u8) {
        self.data = value as *const SecurityDefinitionRejectVLSData;
    }

    #[inline]
    fn set_capacity(&mut self, capacity: u16) {
        self.capacity = capacity as usize;
    }

    #[inline]
    fn set_size(&mut self, size: u16) {
        self.size = size.to_le();
    }
}
/// This is a message from the Server to the Client indicating the Server
/// is rejecting one of the following messages: SymbolsForExchangeRequestVLS,
/// UnderlyingSymbolsForExchangeRequestVLS, SymbolsForUnderlyingRequestVLS,
/// SecurityDefinitionForSymbolRequestVLS, SymbolSearchRequestVLS.
///
/// If there are no symbols to send in response to one of these messages above,
/// then the Server should not send a SecurityDefinitionRejectVLS message
/// and instead send a SecurityDefinitionResponseVLS with only the RequestID
/// and IsFinalMessage fields set. This will be a clear indication to the
/// Client that the request returned no Symbols.
impl SecurityDefinitionReject for SecurityDefinitionRejectVLS {
    type Safe = SecurityDefinitionRejectVLS;
    type Unsafe = SecurityDefinitionRejectVLSUnsafe;

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn request_id(&self) -> i32 {
        i32::from_le(self.request_id)
    }

    /// Text reason for rejection.
    fn reject_text(&self) -> &str {
        get_vls(self, self.reject_text)
    }

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn set_request_id(&mut self, value: i32) -> &mut Self {
        self.request_id = value.to_le();
        self
    }

    /// Text reason for rejection.
    fn set_reject_text(&mut self, value: &str) -> &mut Self {
        self.reject_text = set_vls(self, self.reject_text, value);
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        self
    }
}

/// This is a message from the Server to the Client indicating the Server
/// is rejecting one of the following messages: SymbolsForExchangeRequestVLS,
/// UnderlyingSymbolsForExchangeRequestVLS, SymbolsForUnderlyingRequestVLS,
/// SecurityDefinitionForSymbolRequestVLS, SymbolSearchRequestVLS.
///
/// If there are no symbols to send in response to one of these messages above,
/// then the Server should not send a SecurityDefinitionRejectVLS message
/// and instead send a SecurityDefinitionResponseVLS with only the RequestID
/// and IsFinalMessage fields set. This will be a clear indication to the
/// Client that the request returned no Symbols.
impl SecurityDefinitionReject for SecurityDefinitionRejectVLSUnsafe {
    type Safe = SecurityDefinitionRejectVLS;
    type Unsafe = SecurityDefinitionRejectVLSUnsafe;

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn request_id(&self) -> i32 {
        if self.is_out_of_bounds(12) {
            0i32
        } else {
            i32::from_le(self.request_id)
        }
    }

    /// Text reason for rejection.
    fn reject_text(&self) -> &str {
        if self.is_out_of_bounds(16) {
            ""
        } else {
            get_vls(self, self.reject_text)
        }
    }

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn set_request_id(&mut self, value: i32) -> &mut Self {
        if !self.is_out_of_bounds(12) {
            self.request_id = value.to_le();
        }
        self
    }

    /// Text reason for rejection.
    fn set_reject_text(&mut self, value: &str) -> &mut Self {
        if !self.is_out_of_bounds(16) {
            self.reject_text = set_vls(self, self.reject_text, value);
        }
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }
}

/// This is a message from the Server to the Client indicating the Server
/// is rejecting one of the following messages: SymbolsForExchangeRequestVLS,
/// UnderlyingSymbolsForExchangeRequestVLS, SymbolsForUnderlyingRequestVLS,
/// SecurityDefinitionForSymbolRequestVLS, SymbolSearchRequestVLS.
///
/// If there are no symbols to send in response to one of these messages above,
/// then the Server should not send a SecurityDefinitionRejectVLS message
/// and instead send a SecurityDefinitionResponseVLS with only the RequestID
/// and IsFinalMessage fields set. This will be a clear indication to the
/// Client that the request returned no Symbols.
impl SecurityDefinitionReject for SecurityDefinitionRejectFixed {
    type Safe = SecurityDefinitionRejectFixed;
    type Unsafe = SecurityDefinitionRejectFixedUnsafe;

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn request_id(&self) -> i32 {
        i32::from_le(self.request_id)
    }

    /// Text reason for rejection.
    fn reject_text(&self) -> &str {
        get_fixed(&self.reject_text[..])
    }

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn set_request_id(&mut self, value: i32) -> &mut Self {
        self.request_id = value.to_le();
        self
    }

    /// Text reason for rejection.
    fn set_reject_text(&mut self, value: &str) -> &mut Self {
        set_fixed(&mut self.reject_text[..], value);
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        self
    }
}

/// This is a message from the Server to the Client indicating the Server
/// is rejecting one of the following messages: SymbolsForExchangeRequestVLS,
/// UnderlyingSymbolsForExchangeRequestVLS, SymbolsForUnderlyingRequestVLS,
/// SecurityDefinitionForSymbolRequestVLS, SymbolSearchRequestVLS.
///
/// If there are no symbols to send in response to one of these messages above,
/// then the Server should not send a SecurityDefinitionRejectVLS message
/// and instead send a SecurityDefinitionResponseVLS with only the RequestID
/// and IsFinalMessage fields set. This will be a clear indication to the
/// Client that the request returned no Symbols.
impl SecurityDefinitionReject for SecurityDefinitionRejectFixedUnsafe {
    type Safe = SecurityDefinitionRejectFixed;
    type Unsafe = SecurityDefinitionRejectFixedUnsafe;

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn request_id(&self) -> i32 {
        if self.is_out_of_bounds(8) {
            0i32
        } else {
            i32::from_le(self.request_id)
        }
    }

    /// Text reason for rejection.
    fn reject_text(&self) -> &str {
        if self.is_out_of_bounds(104) {
            ""
        } else {
            get_fixed(&self.reject_text[..])
        }
    }

    /// This is the same RequestID that this message is in response to and was
    /// given in the original request message.
    fn set_request_id(&mut self, value: i32) -> &mut Self {
        if !self.is_out_of_bounds(8) {
            self.request_id = value.to_le();
        }
        self
    }

    /// Text reason for rejection.
    fn set_reject_text(&mut self, value: &str) -> &mut Self {
        if !self.is_out_of_bounds(104) {
            set_fixed(&mut self.reject_text[..], value);
        }
        self
    }

    #[inline]
    fn clone_safe(&self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }

    #[inline]
    fn to_safe(self) -> Self::Safe {
        let mut s = Self::Safe::new();
        self.copy_to(&mut s);
        s
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    #[test]
    pub(crate) fn layout() {
        unsafe {
            assert_eq!(
                104usize,
                core::mem::size_of::<SecurityDefinitionRejectFixedData>(),
                "SecurityDefinitionRejectFixedData sizeof expected {:} but was {:}",
                104usize,
                core::mem::size_of::<SecurityDefinitionRejectFixedData>()
            );
            assert_eq!(
                104u16,
                SecurityDefinitionRejectFixed::new().size(),
                "SecurityDefinitionRejectFixed sizeof expected {:} but was {:}",
                104u16,
                SecurityDefinitionRejectFixed::new().size(),
            );
            assert_eq!(
                SECURITY_DEFINITION_REJECT,
                SecurityDefinitionRejectFixed::new().r#type(),
                "SecurityDefinitionRejectFixed type expected {:} but was {:}",
                SECURITY_DEFINITION_REJECT,
                SecurityDefinitionRejectFixed::new().r#type(),
            );
            assert_eq!(
                509u16,
                SecurityDefinitionRejectFixed::new().r#type(),
                "SecurityDefinitionRejectFixed type expected {:} but was {:}",
                509u16,
                SecurityDefinitionRejectFixed::new().r#type(),
            );
            let d = SecurityDefinitionRejectFixedData::new();
            let p = (&d as *const _ as *const u8).offset(0) as usize;
            assert_eq!(
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
                "size offset expected {:} but was {:}",
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
            );
            assert_eq!(
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
                "type offset expected {:} but was {:}",
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
            );
            assert_eq!(
                4usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
                "request_id offset expected {:} but was {:}",
                4usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
            );
            assert_eq!(
                8usize,
                (core::ptr::addr_of!(d.reject_text) as usize) - p,
                "reject_text offset expected {:} but was {:}",
                8usize,
                (core::ptr::addr_of!(d.reject_text) as usize) - p,
            );
        }
        unsafe {
            assert_eq!(
                16usize,
                core::mem::size_of::<SecurityDefinitionRejectVLSData>(),
                "SecurityDefinitionRejectVLSData sizeof expected {:} but was {:}",
                16usize,
                core::mem::size_of::<SecurityDefinitionRejectVLSData>()
            );
            assert_eq!(
                16u16,
                SecurityDefinitionRejectVLS::new().size(),
                "SecurityDefinitionRejectVLS sizeof expected {:} but was {:}",
                16u16,
                SecurityDefinitionRejectVLS::new().size(),
            );
            assert_eq!(
                SECURITY_DEFINITION_REJECT,
                SecurityDefinitionRejectVLS::new().r#type(),
                "SecurityDefinitionRejectVLS type expected {:} but was {:}",
                SECURITY_DEFINITION_REJECT,
                SecurityDefinitionRejectVLS::new().r#type(),
            );
            assert_eq!(
                509u16,
                SecurityDefinitionRejectVLS::new().r#type(),
                "SecurityDefinitionRejectVLS type expected {:} but was {:}",
                509u16,
                SecurityDefinitionRejectVLS::new().r#type(),
            );
            let d = SecurityDefinitionRejectVLSData::new();
            let p = (&d as *const _ as *const u8).offset(0) as usize;
            assert_eq!(
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
                "size offset expected {:} but was {:}",
                0usize,
                (core::ptr::addr_of!(d.size) as usize) - p,
            );
            assert_eq!(
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
                "type offset expected {:} but was {:}",
                2usize,
                (core::ptr::addr_of!(d.r#type) as usize) - p,
            );
            assert_eq!(
                4usize,
                (core::ptr::addr_of!(d.base_size) as usize) - p,
                "base_size offset expected {:} but was {:}",
                4usize,
                (core::ptr::addr_of!(d.base_size) as usize) - p,
            );
            assert_eq!(
                8usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
                "request_id offset expected {:} but was {:}",
                8usize,
                (core::ptr::addr_of!(d.request_id) as usize) - p,
            );
            assert_eq!(
                12usize,
                (core::ptr::addr_of!(d.reject_text) as usize) - p,
                "reject_text offset expected {:} but was {:}",
                12usize,
                (core::ptr::addr_of!(d.reject_text) as usize) - p,
            );
        }
    }
}
