package rust

import (
	"fmt"
	"time"
)

type Config struct {
	Dir                 string
	RootPackage         string
	FactoryPackage      string
	GeneratedComment    string
	GenerateCopyMethods bool
	GoFmt               bool
	NonStandard         bool
	Json                bool
	Protobuf            bool
	GC                  bool
	NoGC                bool
	TinyGo              bool
	Debug               bool
}

func DefaultConfig(dir string) *Config {
	return &Config{
		Dir:                 dir,
		RootPackage:         "github.com/moontrade/dtc-go/model/v8",
		FactoryPackage:      "factory",
		GeneratedComment:    fmt.Sprintf("generated by github.com/moontrade/dtc-go/codegen/go at %s", time.Now().String()),
		GenerateCopyMethods: false,
		GoFmt:               true,
		NonStandard:         false,
		Json:                true,
		Protobuf:            true,
		GC:                  true,
		NoGC:                true,
		TinyGo:              false,
	}
}

func TinyGoConfig(dir string) *Config {
	return &Config{
		Dir:                 dir,
		RootPackage:         "github.com/moontrade/dtc-go/model/v8",
		FactoryPackage:      "factory",
		GeneratedComment:    fmt.Sprintf("generated by github.com/moontrade/dtc-go/codegen/go at %s", time.Now().String()),
		GenerateCopyMethods: false,
		GoFmt:               true,
		NonStandard:         false,
		Json:                false,
		Protobuf:            false,
		GC:                  true,
		NoGC:                true,
		TinyGo:              true,
	}
}
